# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/logo_miccall.png"
    keywords: Faddy Genius
    backgroundpic : "img/bg.jpg"

Intro:
    name: Faddy Genius
    slogan: "Whatever is worth doing is worth doing well <br/> I'll think of you every step of the way"
    HeadButton: Faddy Genius

Nav:
    Home_name: 主页
    is_use_categories : true 
    categories_name: 分类
    is_use_archives : false
    archives_name: 归档
    
    #Social
    # for more icons, please see http://fontawesome.io/icons/#brand
    icon:
        github: https://github.com/miccall
        500px: http://500px.com
        
    pages:
        简历: 
            link: "/about/"
        团队 :
            link: "/group/"
        图库 :
            link: "/gallery/"
        标签:
            link: "/tag/"
        #自定义标签名
        #   link：“路径”

MainFirst:
    name: Faddy Genius
    description: Technical  Artist  of  Games   
    pic_url: /images/me.jpg
    goto_ulr: ""

Gallery :
    title: Mr.metro 
    description: Just another fine responsive 
# link: 放图片的文件夹名（需放置在主题文件source文件夹下） 
# number: 图片数量 （如需随机设置背景图 要把图片名称重新命名 例如： 1.jpg 2.jpg ... 12.jpg）
article_img:
    link: articleImg
    number: 12
    now_img_url:

# 滚动页面导航是否固定到顶部 
fixed_nav: true
# 建站时间
start_year: 2016
# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System 自定义代码渲染 
# xt256 obsidian monokai isbl-editor-dark idea googlecode github-gist dracula codepen-embed atom-one-dark atom-one-light atelier-dune-dark 优选项
# 比较特殊 brown-paper
# link to review : https://highlightjs.org/static/demo/   官网预览
Highlight:
    enable: true
    link: obsidian

# Custom Fonts
fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
    use: valine
    shortname: http-miccall-tech 
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    # 使用 valine 请先执行 npm install valine --save
    valine: # Valine Comment System https://github.com/xCss/Valine
       on: true
       appId: 'your id'
       appKey: 'your key'
       notify: true
       verify: false
       placeholder: Please leave your footprints
       avatar: ''
       avatar_cdn: https://gravatar.loli.net/avatar/ # avatar CDN address, default gravatar.loli.net
       pageSize: 10 # comments of one page
       visitor: true #是否开启文章统计

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key: Just another fine responsive  
    

# Leancloud Views
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"


# Mathjax 支持库 
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML